name: Mise a jour Hatch NHL Super Pool

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

# Ajouter ces deux lignes pour autoriser le commit/push :
permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Exécuter le script de mise à jour
        run: python scripts/update_data.py

      - name: Publier les modifications dans le dépôt
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git commit -m "Mise à jour automatique des points de la LNH" || exit 0
          git push
